server:
  port: 8080

spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0

judge-authorization:
  user-id: yzl
  user-secret: yzl
  expired-in: 14400
  secret-key: secret

application:
  version: V1.0.0