version: '3'
services:
  judge-host:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_HOST: 172.17.0.1
      REDIS_PORT: 6379
      JUDGE_HOST_USER_ID: yzl
      JUDGE_HOST_USER_SECRET: yzl
      JUDGE_HOST_SECRET_KEY: secret
  redis:
    image: "redis"